import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { document } = await req.json();
    if (!document) return NextResponse.json({ error: 'Missing UDS document payload' }, { status: 400 });

    const extractedData = {
      entities: ["Mocked Entity A", "Mocked Entity B"],
      summary: "This is an AI-extracted summary generated by Anthropic Claude 3.5 Sonnet.",
      engine_type: "Extractor"
    };

    return NextResponse.json({ success: true, analysis: extractedData });
  } catch (error) {
    return NextResponse.json({ error: 'Extraction failed' }, { status: 500 });
  }
}