"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { ShieldAlert, CheckCircle, Scale, FileText, Loader2, Info } from "lucide-react";
import { HiveFooter } from "@/components/HiveFooter";

export default function Home() {
  const [contractText, setContractText] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [auditResult, setAuditResult] = useState<any>(null);
  const [error, setError] = useState("");

  const handleAudit = async () => {
    if (!contractText.trim() || contractText.length < 50) {
      setError("Please paste a valid contract text to audit.");
      return;
    }
    
    setError("");
    setIsProcessing(true);
    setAuditResult(null);
    
    try {
      const res = await fetch('/api/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contractText })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setAuditResult(data);
    } catch (e: any) {
      console.error(e);
      setError(e.message || "Failed to process the contract audit.");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleStripeCheckout = async (action: string) => {
    try {
      const res = await fetch('/api/billing', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action })
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        alert("Stripe configuration error: " + data.error);
      }
    } catch (e) {
      console.error(e);
      alert("Billing system is currently unavailable.");
    }
  };

  return (
    <div style={{ backgroundColor: '#050505', minHeight: '100vh', color: '#ffffff', fontFamily: 'Inter, system-ui, sans-serif', overflowX: 'hidden' }}>
      
      {/* Navigation */}
      <nav style={{ display: 'flex', justifyContent: 'space-between', padding: '1.5rem 4rem', borderBottom: '1px solid rgba(255,255,255,0.05)', backgroundColor: 'rgba(5,5,5,0.8)', backdropFilter: 'blur(12px)', position: 'sticky', top: 0, zIndex: 100 }}>
        <a href="https://hive.baby" target="_blank" rel="noopener noreferrer" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', textDecoration: 'none' }}>
          <div style={{ fontSize: '1.5rem', fontWeight: 'bold', letterSpacing: '-0.02em', paddingLeft: '0.75rem' }}>
            <span style={{ color: '#D4AF37' }}>HiveLegal™</span>
          </div>
        </a>
        <div style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
           <button onClick={() => handleStripeCheckout("enterprise_license")} style={{ backgroundColor: '#ffffff', color: '#000000', padding: '0.5rem 1.25rem', borderRadius: '4px', fontSize: '0.9rem', fontWeight: '500', textDecoration: 'none', transition: 'transform 0.2s', border: 'none', cursor: 'pointer' }}>
            Get Enterprise Key
          </button>
        </div>
      </nav>

      <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '4rem 2rem' }}>
        
        {/* Legal Disclaimer */}
        <div style={{ backgroundColor: 'rgba(255, 0, 0, 0.1)', border: '1px solid rgba(255, 0, 0, 0.3)', borderRadius: '8px', padding: '1rem', marginBottom: '3rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
          <Info color="#ff4444" size={24} />
          <p style={{ margin: 0, fontSize: '0.85rem', color: '#ffaaaa', lineHeight: '1.5' }}>
            <strong>LEGAL DISCLAIMER:</strong> HiveLegal is an autonomous AI analysis engine, not a law firm. The outputs generated by this engine do not constitute legal advice, and no attorney-client relationship is formed. You should consult a licensed attorney in your jurisdiction before signing any legal documents. Use of this service is governed by the Queen Bee protocol.
          </p>
        </div>

        <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
          <div style={{ display: 'inline-block', padding: '0.25rem 1rem', border: '1px solid rgba(212, 175, 55, 0.3)', borderRadius: '20px', color: '#D4AF37', fontSize: '0.85rem', marginBottom: '1.5rem', letterSpacing: '0.05em', textTransform: 'uppercase' }}>
            The Autonomous Redline Engine
          </div>
          <h1 style={{ fontSize: '4.5rem', fontWeight: '900', letterSpacing: '-0.05em', lineHeight: '1', marginBottom: '1rem' }}>
            Don&apos;t Buy Software. <br/>
            <span style={{ background: 'linear-gradient(90deg, #D4AF37 0%, #F3E5AB 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Augment Your Legal Team.</span>
          </h1>
          <p style={{ fontSize: '1.25rem', color: '#a1a1aa', maxWidth: '800px', margin: '0 auto 2.5rem auto', lineHeight: '1.6' }}>
            Paste any contract below. The Maker-Checker protocol will audit it against a strict dealbreaker matrix and instantly generate deterministic redlines. Zero hallucinations.
          </p>
        </div>

        {/* Workspace */}
        <div style={{ display: 'grid', gridTemplateColumns: auditResult ? '1fr 1fr' : '1fr', gap: '2rem', transition: 'all 0.5s ease-in-out' }}>
          
          {/* Input Section */}
          <div style={{ backgroundColor: '#0A0A0C', border: '1px solid rgba(212, 175, 55, 0.2)', borderRadius: '12px', padding: '1.5rem', display: 'flex', flexDirection: 'column' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem', color: '#D4AF37' }}>
              <FileText size={20} />
              <h3 style={{ margin: 0, fontWeight: '600' }}>Paste Contract Text</h3>
            </div>
            <textarea 
              value={contractText}
              onChange={(e) => setContractText(e.target.value)}
              placeholder="Paste the vendor agreement, NDA, or SaaS contract here..."
              style={{ width: '100%', height: '500px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff', padding: '1rem', fontSize: '0.95rem', resize: 'none', outline: 'none' }}
            />
            {error && <p style={{ color: '#ff4444', fontSize: '0.85rem', marginTop: '1rem' }}>{error}</p>}
            
            <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem' }}>
              <button 
                onClick={handleAudit} 
                disabled={isProcessing}
                style={{ flex: 1, backgroundColor: '#D4AF37', color: '#000', border: 'none', padding: '1rem', borderRadius: '8px', fontWeight: '600', fontSize: '1rem', cursor: isProcessing ? 'not-allowed' : 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '0.5rem' }}
              >
                {isProcessing ? <><Loader2 className="animate-spin" size={20} /> Auditing Contract...</> : <><Scale size={20} /> Generate Redlines</>}
              </button>
              {!auditResult && (
                <button 
                  onClick={() => handleStripeCheckout("pay_per_contract")}
                  style={{ backgroundColor: 'transparent', color: '#D4AF37', border: '1px solid #D4AF37', padding: '1rem 1.5rem', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' }}
                >
                  Pay $500 Audit Fee
                </button>
              )}
            </div>
          </div>

          {/* Results Section */}
          {auditResult && (
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} style={{ backgroundColor: '#0A0A0C', border: '1px solid rgba(212, 175, 55, 0.2)', borderRadius: '12px', padding: '2rem', maxHeight: '610px', overflowY: 'auto' }}>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '1rem' }}>
                <h2 style={{ margin: 0, fontSize: '1.5rem', color: '#D4AF37' }}>Audit Results</h2>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', backgroundColor: auditResult.risk_score > 50 ? 'rgba(255,0,0,0.1)' : 'rgba(0,255,0,0.1)', color: auditResult.risk_score > 50 ? '#ff4444' : '#44ff44', padding: '0.5rem 1rem', borderRadius: '20px', fontWeight: 'bold' }}>
                  Risk Score: {auditResult.risk_score}/100
                </div>
              </div>

              <div style={{ marginBottom: '2rem' }}>
                <h3 style={{ color: '#a1a1aa', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Executive Summary</h3>
                <p style={{ fontSize: '1.05rem', lineHeight: '1.6' }}>{auditResult.executive_summary}</p>
              </div>

              <div>
                <h3 style={{ color: '#a1a1aa', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '1rem' }}>Identified Redlines ({auditResult.redlines?.length || 0})</h3>
                
                {auditResult.redlines?.length === 0 ? (
                  <div style={{ padding: '2rem', textAlign: 'center', backgroundColor: 'rgba(0,255,0,0.05)', border: '1px dashed rgba(0,255,0,0.2)', borderRadius: '8px' }}>
                    <CheckCircle color="#44ff44" size={32} style={{ margin: '0 auto 1rem auto' }} />
                    <p style={{ margin: 0 }}>No critical dealbreakers found in this text.</p>
                  </div>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    {auditResult.redlines.map((redline: any, index: number) => (
                      <div key={index} style={{ backgroundColor: 'rgba(255,255,255,0.02)', borderLeft: \`4px solid \${redline.severity === 'critical' ? '#ff4444' : '#D4AF37'}\`, padding: '1.5rem', borderRadius: '0 8px 8px 0' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.75rem' }}>
                          <ShieldAlert size={16} color={redline.severity === 'critical' ? '#ff4444' : '#D4AF37'} />
                          <span style={{ fontSize: '0.85rem', fontWeight: 'bold', textTransform: 'uppercase', color: redline.severity === 'critical' ? '#ff4444' : '#D4AF37' }}>{redline.severity}</span>
                        </div>
                        <p style={{ fontSize: '0.95rem', color: '#a1a1aa', marginBottom: '0.5rem' }}><strong>Violation:</strong> {redline.issue_description}</p>
                        <div style={{ backgroundColor: 'rgba(255,0,0,0.05)', padding: '0.75rem', borderRadius: '4px', marginBottom: '0.75rem', fontSize: '0.9rem', border: '1px solid rgba(255,0,0,0.1)' }}>
                          <span style={{ textDecoration: 'line-through', opacity: 0.8 }}>{redline.clause_excerpt}</span>
                        </div>
                        <div style={{ backgroundColor: 'rgba(0,255,0,0.05)', padding: '0.75rem', borderRadius: '4px', fontSize: '0.9rem', border: '1px solid rgba(0,255,0,0.1)', color: '#aaffaa' }}>
                          <strong>Recommended Revision:</strong><br/>
                          {redline.recommended_revision}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </motion.div>
          )}

        </div>
      </main>

      <HiveFooter />
    </div>
  );
}
